[tool.poetry]
name = "market-research-agent"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.2.0"
langchain-openai = "^0.1.0"
langgraph = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
